In [1]:
import pandas as pd
import numpy as np

In [2]:
d = pd.read_csv(r"C:\Users\ponra\Downloads\Swarm_Behaviour.csv\Swarm_Behaviour.csv")

In [5]:
d.head()

x1      y1  xVel1  yVel1   xA1   yA1  xS1  yS1   xC1   yC1  ...  \
0   562.05   -0.62 -10.70  -4.33  0.00  0.00  0.0  0.0  0.00  0.00  ...   
1   175.66  -57.09   2.31  -2.67  0.00  0.00  0.0  0.0  0.00  0.00  ...   
2   200.16 -320.07   4.01  -6.37  0.00  0.00  0.0  0.0  0.18 -0.26  ...   
3   316.99 -906.84   0.85   9.17 -0.17  1.03  0.0  0.0  0.00  0.00  ...   
4  1277.68  908.54  -2.02   8.23 -1.00  1.00  0.0  0.0  0.00  0.00  ...   

   yVel200  xA200  yA200  xS200  yS200  xC200  yC200  nAC200  nS200  \
0   -15.15   0.00   0.00   0.00   0.00   0.00    0.0      28      0   
1    -3.48   0.00   0.00   0.00   0.00   0.00    0.0       4      0   
2    -9.38   0.00   0.00   0.00   0.00  -0.11   -0.3      15      1   
3    10.39  -0.26   1.01   0.00   0.00   0.00    0.0      16      0   
4    13.91  -1.00   0.00   3.21  15.67   0.00    0.0      12      0   

   Swarm_Behaviour  
0              0.0  
1              0.0  
2              0.0  
3              0.0  
4              0.0  

[5 rows x 2401 columns]

In [14]:
print(d.isnull().any()==False)

x1                 True
y1                 True
xVel1              True
yVel1              True
xA1                True
                   ... 
xC200              True
yC200              True
nAC200             True
nS200              True
Swarm_Behaviour    True
Length: 2401, dtype: bool


In [7]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23309 entries, 0 to 23308
Columns: 2401 entries, x1 to Swarm_Behaviour
dtypes: float64(2001), int64(400)
memory usage: 427.0 MB


In [10]:
x = d.iloc[:,:-1].values
y = d['Swarm_Behaviour']

# Logistic Regression

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [17]:
from sklearn.linear_model import LogisticRegression
logi = LogisticRegression()
logi.fit(x_train,y_train)
y_pred = logi.predict(x_test)

C:\Users\ponra\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [18]:
y_pred

array([1., 0., 1., ..., 1., 0., 0.])

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_pred,y_test)

array([[3496,  368],
       [ 348, 1616]], dtype=int64)

In [20]:
accuracy_score(y_pred,y_test)

0.8771448181194235

# KNN

In [22]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)

In [23]:
confusion_matrix(y_pred,y_test)

array([[3543,  359],
       [ 301, 1625]], dtype=int64)

In [24]:
accuracy_score(y_pred,y_test)

0.8867536032944406

# Naive Bayes

In [26]:
from sklearn.naive_bayes import GaussianNB
gb = GaussianNB()
gb.fit(x_train,y_train)
y_pred = gb.predict(x_test)

In [27]:
y_pred

array([1., 1., 1., ..., 1., 1., 1.])

In [28]:
accuracy_score(y_pred,y_test)

0.47168840082361013

# Decision Tree

In [29]:
from sklearn.tree import DecisionTreeClassifier
ds = DecisionTreeClassifier()
ds.fit(x_train,y_train)
y_pred = ds.predict(x_test)

In [30]:
y_pred

array([1., 0., 1., ..., 1., 0., 0.])

In [31]:
accuracy_score(y_pred,y_test)

0.8695950583390528